apiVersion: v1
kind: Service
metadata:
  name: {{ include "goose.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "goose.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
